### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by csujaan** [OhMyGuus/BetterCrewlink-mobile#11]
Maybe add a refresh button! It's hard to refresh here. Whenever I switch from the game to app to refresh it kicks me out (obviously!). It can be a notification shade button too.

**Comment by OhMyGuus** [comment]
yes it was a notification before, will be fixed again in next update, which will be soon preparing some things now so I can work easier on the mobile app.

**Comment by OhMyGuus** [comment]
The notification has been fixed.
