### ISSUE TITLE
[BUG REPORT] Possible bug with new version of Among Us with BetterCrewLink Mobile

### ISSUE THREAD

**Issue by MatadorProBr** [OhMyGuus/BetterCrewlink-mobile#15]
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
3. [X] I have checked everyone in my lobby is on the same CrewLink server
4. [X] I have used `Refresh` on the CrewLink app when I can't hear some people (this is a known issue)
5. [X] I have checked that the CrewLink server I'm using is up to date
6. [ ] I have a screenshot of any errors
7. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewlink-mobile/issues?q=is%3Aissue)

**Describe the bug**
Several users on the BetterCrewLink Discord are reporting that the Mobile version is not working, that is, they literally listen to everyone but no one listens to the person and I think this could be a possible update bug for Among Us as he reported that this happened later of the update and yes, I made him check if he has enabled NAT Fix, if he has used the same Voice Server that others are using and also said that the person on the PC has activated the Mobile Host option in the settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'BetterCrewLink Mobile'
2. Click on 'Connect'
3. See error of nobody listen you

**Expected behaviour**
It was so that everyone can hear the cell phone player but for some reason it doesn't.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [For each person and with a different Android]
 - Version: [1.0.20 and 1.0.24 beta version]

**Additional context**
N/A

**Comment by MatadorProBr** [comment]
![image](https://user-images.githubusercontent.com/71022656/111612310-1e7c5c00-87bc-11eb-9a71-6c097e72724a.png)

**Comment by MatadorProBr** [comment]
Edit: Apparently it is not just the problem of listening to people and yes it can crash, Refresh button does not work so in reality I suspect that it is an error within the application and not with the PC application with the "Mobile Host" function and it looks like there are some solutions to solve this:

There are "2 solutions" for that

1 - Try to download the BETA version of BetterCrewLink Mobile: https://mirror.bettercrewl.ink/beta/BetterCrewlink-1-0-24-beta.apk
2 - Try using the web version: https://web.bettercrewl.ink/

from what I have already tested on other people the solution to download the BETA version didn’t change at all and continued the same error but using the web version solved practically for almost everyone

**Comment by MatadorProBr** [comment]
For people who have this bug, try to download the version: https://mirror.bettercrewl.ink/beta/BetterCrewlink-1-0-25-beta.apk in your cellphone and test to see if it is working because it is a BETA version, and if you find a bug use any of the platforms below to report the bug because if you do not report we will not fix it because we do not know if there will be a bug or not:

Talk to us on our [Discord](https://discord.gg/qDqTzvj4SH), or [GitHub](https://github.com/OhMyGuus/BetterCrewLink/issues) or message on Discord ([ThaGuus#2140](https://discordapp.com/users/508426414387757057))

**Comment by OhMyGuus** [comment]
There is also a bug in current version that it doesn't start the mobile host anymore. Let someone refresh there Crewlink after joining the game to resolve this atm. This issue will be fixed with the new release at 31 march

**Comment by MatadorProBr** [comment]
Resolved in the new update of BetterCrewLink Mobile
