### ISSUE TITLE
Cannot find "Mobile host" in my settings

### ISSUE THREAD

**Issue by maelwawi** [OhMyGuus/BetterCrewlink-mobile#6]
Hello there,

I just install Crewlink PC Version but i cannot find mobile host in my settings, so my friend cannot join.

What Can I do ?

TY

**Comment by OhMyGuus** [comment]
https://github.com/OhMyGuus/BetterCrewLink/releases 

Mobile host is only on bettercrewlink

**Comment by MatadorProBr** [comment]
Close this owo
