### ISSUE TITLE
Delay on Mobile

### ISSUE THREAD

**Issue by Kelbie** [OhMyGuus/BetterCrewlink-mobile#9]
Sometimes talking to mobile users can an issue because they often have a delay anywhere from 5-60 seconds.

**Comment by Steby5** [comment]
> 
> 
> Sometimes talking to mobile users can an issue because they often have a delay anywhere from 5-60 seconds.

60 sec?! I experience at most like 2sec.

**Comment by Kelbie** [comment]
Yeah we have had someone with a 60 second delay before, very unplayable.

**Comment by MatadorProBr** [comment]
Probably now there should be no more delay because of the updates that have done that changed a lot of things and must have fixed it
if not corrected go to the [BetterCrewLink Discord](https://discord.gg/qDqTzvj4SH) and open a ticket or speak on the channel bettercrewlink-help

**Comment by MatadorProBr** [comment]
Close this owo
